---
- name: EC2 on BIG-IP Create
  hosts: localhost
  connection: local
  gather_facts: False

  rolse:
    - big-ip

- name: Get Inventory
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

